# Generated by Django 4.2.14 on 2024-10-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='project',
            name='duration',
        ),
        migrations.AddField(
            model_name='project',
            name='contractor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
