# Generated by Django 4.2.14 on 2024-10-16 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_contractor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='scope_of_works',
        ),
        migrations.CreateModel(
            name='ScopeOfWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_of_works', to='projects.project')),
            ],
        ),
    ]
