# Generated by Django 4.2.14 on 2024-10-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_scope_of_works_scopeofworks'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completed',
            field=models.DateField(default='2020-01-01'),
            preserve_default=False,
        ),
    ]
