# Generated by Django 4.2.14 on 2024-08-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='description',
            new_name='alt',
        ),
        migrations.AddField(
            model_name='media',
            name='cover_photo',
            field=models.BooleanField(default=False),
        ),
    ]
