# Generated by Django 4.2.14 on 2024-10-17 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_rename_description_media_alt_media_cover_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='uploaded_at',
        ),
    ]
